const CONSTANTS = {
  STATUS_STREAM_IDLE: 0,
  STATUS_STREAM_ERROR: -1,
  STATUS_STREAM_WAITING: 1,
  STATUS_STREAM_DONE: 2,

  SOCKET_IO_ENDPOINT_DEV: 'http://localhost:3000',
  SOCKET_IO_ENDPOINT_PROD: 'TODO',

  // video sizes - TODO: scale page collapse
  VIDEO_THUMBNAIL_WIDTH: 160,
  VIDEO_THUMBNAIL_HEIGHT: 90,
  VIDEO_STREAMS_WIDTH: 320,
  VIDEO_STREAMS_HEIGHT: 180,
  VIDEO_MAIN_WIDTH: 640,
  VIDEO_MAIN_HEIGHT: 360,

  // pages
  PAGE_LANDING: 0,
  PAGE_SEARCH_RESULTS: 1,
  PAGE_SEARCH_RESULTS_NONE: 2,
  PAGE_INCIDENT_VIEWER: 3,
  PAGE_LIVE_STREAM: 4,
  PAGE_OBJECT_SET: 5,
};

export default CONSTANTS;
