const CONSTANTS = {
  STATUS_STREAM_IDLE: 0,
  STATUS_STREAM_ERROR: -1,
  STATUS_STREAM_WAITING: 1,
  STATUS_STREAM_DONE: 2,

  SOCKET_IO_ENDPOINT_DEV: 'http://localhost:3000',
  SOCKET_IO_ENDPOINT_PROD: 'TODO',
};

export default CONSTANTS;
