const CONSTANTS = {
  STATUS_STREAM_IDLE: 0,
  STATUS_STREAM_ERROR: -1,
  STATUS_STREAM_WAITING: 1,
  STATUS_STREAM_DONE: 2,

  SOCKET_IO_ENDPOINT_DEV: 'http://localhost:3000',
  SOCKET_IO_ENDPOINT_PROD: 'TODO',

  VIDEO_THUMBNAIL_WIDTH: 320,
  VIDEO_THUMBNAIL_HEIGHT: 180,

  VIDEO_MAIN_WIDTH: 640,
  VIDEO_MAIN_HEIGHT: 360,

  // TODO
  VIDEO_STREAMS_WIDTH: 0,
  VIDEO_STREAMS_HEIGHT: 0,
};

export default CONSTANTS;
